### ISSUE TITLE
Prusa: state handling when printer is restarted/shutdown during printing

### ISSUE THREAD

**Issue by jichengzhi** [monash-automation/mes-printing-server#45]
The printer is shutdown manually during printing because an heating error is raised.

```text
2024-02-20 00:43:59,246 - ERROR - PrinterWorker2 http://172.32.1.165 - [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/app/src/worker/core.py", line 93, in run
    await self.step()
  File "/app/src/worker/core.py", line 72, in step
    stat = await self.actual_printer.current_status()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/printer/prusa/core.py", line 28, in current_status
    async with self.get("/api/v1/status") as resp:
  File "/app/.venv/lib/python3.11/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/aiohttp/client.py", line 605, in _request
    await resp.start(conn)
  File "/app/.venv/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 966, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
```

The job status in DB is updated to `printed` after re-syncing the printer state in the printer worker.

**Comment by jichengzhi** [comment]
Connection error and other http errors are caught and logged
