### ISSUE TITLE
Prusa: unhandled state "busy"

### ISSUE THREAD

**Issue by jichengzhi** [monash-automation/mes-printing-server#46]
```text
2024-03-04 11:05:34,966 - ERROR - Worker-Printer2 - busy
Traceback (most recent call last):
  File "/Users/jichengzhi/Documents/GitHub/mes-printing-server/src/worker/core.py", line 106, in run
    await self.step()
  File "/Users/jichengzhi/Documents/GitHub/mes-printing-server/src/worker/core.py", line 85, in step
    stat = await self.printer.actual.current_status()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jichengzhi/Documents/GitHub/mes-printing-server/src/printer/prusa/core.py", line 34, in current_status
    state=parse_state(model.printer.state),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jichengzhi/Documents/GitHub/mes-printing-server/src/printer/prusa/core.py", line 20, in parse_state
    raise ValueError(other)
ValueError: busy
```

**Comment by jichengzhi** [comment]
Currently the "busy" is treated as "error" because the printer cannot respond API requests if busy.
